### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by CliffHan** [svartalf/rust-battery#59]
I tried to add android support with same configuration as "target_os=linux", and it works.

Please add android support.

**Comment by svartalf** [comment]
While it might work on some devices, in a whole accessing battery state on Android via `sysfs` is unreliable for many reasons, see https://issuetracker.google.com/issues/37095733 

Due to this fact, I'm prefer to decline #60 till we will get an official way to get battery information on the NDK level without Java/Kotlin/etc middleware.

**Comment by CliffHan** [comment]
I see, thanks for your explanation.
